version: "3"

services:
  stairspeedtest-docker:
    image: quzard/stairspeedtest:amd64
    container_name: stairspeedtest-docker
    restart: always
    ports:
        - "127.0.0.1:65430:65430" #将宿主机8087端口映射到docker的80端口
    volumes:
      - ./results:/speedtest/results
  utility.watchtower:
    container_name: watchtower_stairspeedtest
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
    restart: always