version: "3"

services:
  stairspeedtest:
    image: quzard/stairspeedtest:latest
    container_name: stairspeedtest
    restart: always
    ports:
        - "65430:65430" #将宿主机8087端口映射到docker的80端口
    volumes:
      - ./results:/speedtest/results
      - ./logs:/speedtest/logs
