name: Docker

on:
  schedule:
    - cron: '05 22 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天UTC时间的22点05分整， 北京时间的06点05分（24小时制）
    # 可在此网站查询UTC时间和北京时间的换算关系 https://datetime360.com/cn/utc-beijing-time/
  watch:
    types: started

jobs:
  push_amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Push image
        run: |
          echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u quzard --password-stdin
          cd Build-test/amd64
          sudo docker build -t='quzard/stairspeedtest:amd64' .
          sudo docker push quzard/stairspeedtest:amd64
  push_arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Push image
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: aarch64
          distro: ubuntu20.04
          run: |
            echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u quzard --password-stdin
            cd Build-test/arm64
            sudo docker build -t='quzard/stairspeedtest:arm64' .
            sudo docker push quzard/stairspeedtest:arm64
